version: v1.0
name: Build Kernel

agent:
  machine:
    type: e1-standard-2

  containers:
    - name: main
      image: 'baalajimaestro/kernel_build:latest'

blocks:
  - name: "Build"
    task:
      jobs:
      - name: Build
        commands:
          - echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
          - chmod 600 ~/.ssh/config
          - checkout
          - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          - pip3 install --user GitPython aiogram
          - python3 build.py
      secrets:
        - name: api-keys